### ISSUE TITLE
What to set host value in elasticsearch-curator.yaml

### ISSUE THREAD

**Issue by hectoralicea** [timfpark/fabrikate-cloud-native-materialized#1]
Not sure where to post this, but
I'm seeing this in prod/elasticsearch-fluentd-kibana/elasticsearch-curator.yaml

```
  config.yml: |-
    ---
    client:
      hosts:
        - CHANGEME.host
```
I have no idea what the host name should be.

How should I go about figureing out what the host name should be?
